server:
  port: 8080
  servlet:
    context-path: /shiro

spring:
  application:
    name: shiro-integrated-spring-boot
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.8.6:3306/db_shiro?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:top/simba1949/mapper/*.xml
  type-aliases-package: top.simba1949.entity
